### ISSUE TITLE
Regarding first run

### ISSUE THREAD

**Issue by vishalofficial965** [JeetKaria06/CF_Submissions#3]
Hi,i forked this repo,ran 
1)pip install -r prerequesites.txt
2)python scrap-cf-sub.py --handle myusername --dir c:/random_directory_in_my_system
**i got error-**
**python: can't open file 'scrap-cf-sub.py': [Errno 2] No such file or directory**

Although i checked ive file 'scrap-cf-sub.py' in my 'Scrapping_Submissions' folder .
Help me :D

**Comment by JeetKaria06** [comment]
You need to clone the whole repository and store it anywhere in one of your local directories and then change your path in terminal to that repo and then run it.
Hopefully, it will work : )
Do let me know if it doesn't.
